### ISSUE TITLE
Gambio 3.12 compatibility 

### ISSUE THREAD

**Issue by raptoni** [wirecard/gambio-wcp#46]
When will the plugin be compatible with version 3.12?

**Comment by rinnhofer** [comment]
Hello @raptoni ,

we are already working on a final compatibility check with version 3.12 and adaptions in our codebase.
We will inform you as soon as we are finished with our final tests.

Kind regards,
Wirecard Shop Systems Team

**Comment by rinnhofer** [comment]
Hello @raptoni ,

we are now compatible with Gambio 3.12.x with our newest release:
https://github.com/wirecard/gambio-wcp/releases/tag/2.3.0

Kind regards,
Wirecard Shop Systems Team
