### ISSUE TITLE
wcp2.3 - Gambio 3.10.3.0 - PHP 7.2 - Lots of Warnings

### ISSUE THREAD

**Issue by dahuafschmied** [wirecard/gambio-wcp#47]
No problems with PHP 7.1

For example:
MODULE_PAYMENT_WCP_ORDER_STATUS_FAILED is defined in checkout_page_confirm.php
and used in checkout_page_callback.php but not included there.

![Bildschirmfoto 2019-05-17 um 14 03 24](https://user-images.githubusercontent.com/3955019/57926886-cbc67600-78ac-11e9-818f-f021f74099ae.png)

**Comment by dahuafschmied** [comment]
My fault. PHP7.2-SOAP was missing.

**Comment by jakubpolomsky** [comment]
Thank you nevertheless for your report and solution!

Wirecard team
