### ISSUE TITLE
PSD2 compatible Plugin

### ISSUE THREAD

**Issue by raptoni** [wirecard/gambio-wcp#49]
Will there be a PSD2 compatible Plugin before the 14.9? the repo gambio.wirecard.com is still pretty empty

**Comment by vitali-graz** [comment]
Hello @raptoni,
the development of this shop extension will not be continued in the near future and it will become obsolete in the long run. This means that additional functionality like the PSD2 support will not be implemented.
Please take a look at our online documentation, which describes in more detail how to integrate the Wirecard Payment Gateway into your online shop.
If you have any questions, please contact shop-systems-support@wirecard.com
We plan to introduce a new Gambio extension either as an integration or as a separate extension but cannot announce any concrete dates as of now.
Best regards,
Wirecard Shop Extensions Team
